---
- name: check current docker version
  command: docker --version
  register: docker_version
  changed_when: false
  failed_when: false

- name: Uninstall Docker if version is less than 17.03
  package:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker
    - docker-common
    - docker-engine
  when: >
    docker_version.stdout is defined
    and docker_version.stdout | version_compare("17.03", "<")

- name: Copy Docker repo file
  template:
    src: "/etc/ansible/roles/docker/templates/docker-ce.repo.j2"
    dest: "/etc/yum.repos.d/docker-ce.repo"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Install Content-Selinux for Docker
  yum:
    name: http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.21-1.el7.noarch.rpm
    state: present

- name: Install necessary packages
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - unzip
    - wget
  tags: docker

- name: Install Docker
  yum:
    name: docker-ce
    state: latest
  tags: docker

- name: Make sure Docker is running and Enabled at boot time
  service:
    name: docker
    state: started
    enabled: yes
  tags: docker

- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.19.0/docker-compose-Linux-x86_64"
    dest: "/usr/local/bin/docker-compose"
    force: True
    owner: "root"
    group: "root"
    mode: "0755"

- name: Get Black Duck Installation package
  unarchive:
    src: https://github.com/blackducksoftware/hub/archive/v4.4.0.tar.gz
    dest: /root/
    remote_src: yes

- name: Run docker-compose
  shell: "COMPOSE_HTTP_TIMEOUT=200 docker-compose -f docker-compose.yml -p hub up -d"
  args:
    chdir: /root/hub-4.4.0/docker-compose/
  tags: Black_Duck
